version: "3.3"

services:
  signer-router:
    container_name: signer-router
    image: "ghcr.io/connext/web3signer:latest"
    restart: always
    environment:
      - WEB3_SIGNER_PRIVATE_KEY=$WEB3_SIGNER_PRIVATE_KEY_ROUTER
      - WEB3SIGNER_HTTP_HOST_ALLOWLIST=*
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  router-cache:
    container_name: router-cache
    image: redis:latest
    ports:
      - "6379:6379"

  signer-sequencer:
    container_name: signer-sequencer
    image: "ghcr.io/connext/web3signer:latest"
    restart: always
    environment:
      - WEB3_SIGNER_PRIVATE_KEY=$WEB3_SIGNER_PRIVATE_KEY_SEQUENCER
      - WEB3SIGNER_HTTP_HOST_ALLOWLIST=*
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  message-queue:
    container_name: message-queue
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"

  sequencer-cache:
    container_name: sequencer-cache
    image: redis:latest
    ports:
      - "6380:6379"

  relayer:
    container_name: relayer
    depends_on:
      - sequencer-subscriber
    image: ${RELAYER_IMAGE}
    restart: always
    ports:
      - "8082:8080"
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ${PWD}/docker/relayer/:/home/node/agents/relayer/
      - ${PWD}/docker/relayer/config.local.json:/home/node/packages/agents/relayer/config.json

  signer-relayer:
    container_name: signer-relayer
    image: "ghcr.io/connext/web3signer:latest"
    restart: always
    environment:
      - WEB3_SIGNER_PRIVATE_KEY=$WEB3_SIGNER_PRIVATE_KEY_RELAYER
      - WEB3SIGNER_HTTP_HOST_ALLOWLIST=*
    logging:
      driver: json-file
      options:
        max-size: 10m
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

  relayer-cache:
    container_name: relayer-cache
    image: redis:latest
    ports:
      - "6381:6379"
