version: "3.3"

services:
  router:
    env_file:
      - .env
    image: ${ROUTER_IMAGE}
    restart: always
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ${PWD}/docker/sequencer/config.json:/home/node/agents/sequencer/config.json
  sequencer:
    image: ${SEQUENCER_IMAGE}
    restart: always
    ports:
      - "8081:8081"
    logging:
      driver: json-file
      options:
        max-size: 10m
    volumes:
      - ${PWD}/docker/sequencer/config.json:/home/node/agents/sequencer/config.json
  redis:
    image: redis:latest
    container_name: rd01
    ports:
      - "6379:6379"
