[profile.default]
src = 'contracts_forge'
out = 'artifacts_forge'
libs = ["node_modules", "lib"]
block_timestamp = 1648744712
solc_version = '0.8.17'
# See more config options https://github.com/gakonst/foundry/tree/master/config


[rpc_endpoints]
mainnet = "https://cloudflare-eth.com"
goerli = "https://goerli.infura.io/v3/7672e2bf7cbe427e8cd25b0f1dde65cf"

optimism = "https://mainnet.optimism.io"
optimism_goerli = "https://optimism-goerli.infura.io/v3/7672e2bf7cbe427e8cd25b0f1dde65cf"

arbitrum_one = "https://arb1.arbitrum.io/rpc"
arbitrum_one_goerli = "https://arbitrum-goerli.infura.io/v3/7672e2bf7cbe427e8cd25b0f1dde65cf"

polygon = "https://1rpc.io/matic"
polygon_mumbai = "https://rpc.ankr.com/polygon_mumbai"

bnb_smart_chain = "https://bsc-dataseed.binance.org/"
bnb_smart_chain_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

gnosis_chain = "https://rpc.gnosischain.com/"