version: "3.8"

services:
  ##########################
  router:
    container_name: router-test
    image: nxtp-router:latest
    ports:
      - 8080:8080
    volumes:
      - ./config.json:/home/node/router/config.json
    depends_on:
      - chain-1337
      - chain-1338
    networks:
      - nxtp-test
  ##########################

  ##########################
  chain-1337:
    container_name: chain-1337-test
    image: trufflesuite/ganache-cli:latest
    command: "--chainId 1337 --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --hostname 0.0.0.0 --blockTime 5 --verbose"
    ports:
      - 8545:8545
    networks:
      - nxtp-test
  chain-1338:
    container_name: chain-1338-test
    image: trufflesuite/ganache-cli:latest
    command: "--chainId 1338 --mnemonic 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' --host 0.0.0.0 --blockTime 5 --verbose"
    ports:
      - 8546:8545
    networks:
      - nxtp-test
  ##########################

  ##########################
  graph-node-1337:
    container_name: graph-node-1337-test
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres-1337
      - chain-1337
    environment:
      postgres_host: postgres-1337
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "mainnet:http://chain-1337:8545"
      GRAPH_LOG: info
    networks:
      - nxtp-test
  postgres-1337:
    container_name: postgres-1337-test
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    networks:
      - nxtp-test
  graph-node-1338:
    container_name: graph-node-1338-test
    image: graphprotocol/graph-node
    ports:
      - "9000:8000"
      - "9001:8001"
      - "9020:8020"
      - "9030:8030"
      - "9040:8040"
    depends_on:
      - ipfs
      - postgres-1338
      - chain-1338
    environment:
      postgres_host: postgres-1338
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      ethereum: "mainnet:http://chain-1338:8545"
      GRAPH_LOG: info
    networks:
      - nxtp-test
  postgres-1338:
    container_name: postgres-1338-test
    image: postgres
    ports:
      - "5433:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    networks:
      - nxtp-test
  ipfs:
    container_name: ipfs-test
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - "5001:5001"
    networks:
      - nxtp-test
  ##########################

  auth:
    container_name: auth-test
    image: "connextproject/nats-auth"
    environment:
      VECTOR_JWT_SIGNER_PUBLIC_KEY_PATH: "/pub.key"
      VECTOR_JWT_SIGNER_PRIVATE_KEY_PATH: "/priv.key"
      VECTOR_NATS_URL: "nats://nats:4222"
      VECTOR_ADMIN_TOKEN: "connext1234"
      VECTOR_PORT: "5040"
      VECTOR_PROD: "true"
    ports:
      - "5040:5040"
    volumes:
      - "./pub.key:/pub.key"
      - "./priv.key:/priv.key"
    networks:
      - nxtp-test

  nats:
    container_name: nats-test
    image: "connextproject/vector_nats"
    environment:
      JWT_SIGNER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwQYLqNYRZrZcbD7Dx82b
        rIiuOt2XSBI6oAYPb8WcnX1me4UyfVsx7eIF+DnyOJ7sinaG6hwx7zuyUPGy0QkI
        YycNp2XX9BhA7zkWkrkIUAy9N/2Onq/HGXmaCGQQ6MMlopaz6ryuKmatCcWHUbBW
        R/y2I79kK7IulWAJoX0yt867MToj8bEwlc8BIzqsWV+IwiXps5nX5PUHk/nwWMXI
        JYYTE2VpJhwrkuw2R2VuaHxYoNneDlgNN/EJtZuqrAheqNBcd+Jyujpo4uaieIGC
        tBdYy9hoxaBYhR82SGClFoRGWD4cb/3GTYXJf7ZaZrg/zkqEvrks6FNsFPeCslYM
        A/jlFQNkoVUSn15n1B7ndetebEIRtFkaVQ89Ejxr3oHGdG2i6OAnuEQpAUOsG9Fu
        sHv61RMCo+CcWwT1yMACcxWfN/aL9dOE+zDtQXSM1P5wYOHBaCHOnyCaumyieZ7v
        sxGKQmfS/PtUWZTpHHdsafaVpUxkq0YFx5VzFbqraQf3AFU1wRaJYm6JNdHCLpVg
        XBYYKUz9kGFJMe0T21AUeV53gi1yUwy6+jJQJbdV9bCtZnUQi7YlWmIrE25ABs2O
        DvKsD63QcBOW4TATrd6+zUX3n80ZGz/60oS4SPOBmlGjdoZD9bASYCNrqJTBSegA
        /jwvk787srHfu0XqjeY3DAkCAwEAAQ==
        -----END PUBLIC KEY-----"
    ports:
      - "4222:4222"
      - "4221:4221"
    networks:
      - nxtp-test

networks:
  nxtp-test:
