version: "3.9"
services:
  chain_1337:
    container_name: chain_1337
    image: trufflesuite/ganache-cli:latest
    command: --chainId 1337 --hostname 0.0.0.0 --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    ports:
      - "8545:8545"
  chain_1338:
    container_name: chain_1338
    image: trufflesuite/ganache-cli:latest
    command: --chainId 1338 --hostname 0.0.0.0 --mnemonic "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    ports:
      - "8546:8545"
