name: Create and publish Docker images

on:
  push:
    branches:
      - amarok
  pull_request:
    branches:
      - amarok
  create:
    tag:
      - "v*"

env:
  REGISTRY: ghcr.io
  ROUTER_IMAGE_NAME: connext/router
  SEQUENCER_IMAGE_NAME: connext/sequencer

jobs:
  build-and-push-router-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker - router
        id: meta-router
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.ROUTER_IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image - router
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta-router.outputs.tags }}
          labels: ${{ steps.meta-router.outputs.labels }}
          file: docker/router/Dockerfile

      - name: Extract metadata (tags, labels) for Docker - sequencer
        id: meta-sequencer
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.SEQUENCER_IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image - sequencer
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta-sequencer.outputs.tags }}
          labels: ${{ steps.meta-sequencer.outputs.labels }}
          file: docker/sequencer/Dockerfile

      - name: Terraform fmt
        uses: hashicorp/setup-terraform@v1
        id: fmt
        run: cd ops && terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        uses: hashicorp/setup-terraform@v1
        id: init
        run: cd ops && terraform init

      - name: Terraform Validate
        uses: hashicorp/setup-terraform@v1
        id: validate
        run: cd ops && terraform validate -no-color

      - name: Terraform Plan
        uses: hashicorp/setup-terraform@v1
        id: plan
        env:
          TF_VAR_AWS_SECRET: ${{ secrets.AWS_SECRET }}
          TF_VAR_AWS_KEY: ${{ secrets.AWS_KEY }}
        run: cd ops && terraform plan -no-color  -var full_image_name_router='${{steps.meta-router.outputs.tags}}' -var full_image_name_sequencer='${{steps.meta-sequencer.outputs.tags}}'
        continue-on-error: true

      - name: Terraform Docker Image onto AWS
        uses: hashicorp/setup-terraform@v1
        id: apply
        env:
          TF_VAR_AWS_SECRET: ${{ secrets.AWS_SECRET }}
          TF_VAR_AWS_KEY: ${{ secrets.AWS_KEY }}
        run: |
          cd ops && terraform apply -var full_image_name_router='${{steps.meta-router.outputs.tags}}' -var full_image_name_sequencer='${{steps.meta-sequencer.outputs.tags}}' -auto-approve
