# A GitHub Actions workflow to build a docker image for an app.
#
# One-time setup to use this workflow:
# 1. Move this file into ./.github/workflows
# 2. Change APP_NAME variable below to the name of the app.
#
# The image will be built on each push to or pull request on main.
# It will be pushed to the current GitHub repo's Packages.

name: Build and Push Docker Image - Router

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    tag:
      - "v*"

env:
  # These variables are used by build.sh.

  # Comment out the following line to skip pushing the image to your GitHub repo.
  DOCKER_REPO: ghcr.io

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add COMMIT_HASH env property with commit short sha
        run: echo "COMMIT_HASH=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - name: Build and push docker image to GitHub repo
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          chmod +x ./docker/build-router.sh
          ./docker/build-router.sh
